# Generated by Django 3.1.7 on 2021-03-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_images_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='key',
            new_name='product',
        ),
    ]
